import json

nb_path = 'main.ipynb'
try:
    with open(nb_path, 'r', encoding='utf-8') as f:
        nb = json.load(f)
except Exception as e:
    print(f"Error reading notebook: {e}")
    exit(1)

# Completely replace cell 2 and 3 code to use PIL
cell2_source = [
    "import random\n",
    "import matplotlib.pyplot as plt\n",
    "from PIL import Image\n",
    "import numpy as np\n",
    "import matplotlib.patches as patches\n",
    "from collections import Counter\n",
    "\n",
    "def get_class_distributions_and_resolutions(blue_1_files, blue_2_files): \n",
    "    classes = []\n",
    "    widths = []\n",
    "    heights = []\n",
    "    fruit_counts = []\n",
    "    \n",
    "    datasets = [blue_1_files, blue_2_files]\n",
    "    for dataset in datasets:\n",
    "        for txt_file in dataset['labels_txt']:\n",
    "            with open(txt_file, 'r') as f:\n",
    "                lines = f.readlines()\n",
    "                fruit_counts.append(len(lines))\n",
    "                for line in lines:\n",
    "                    parts = line.strip().split()\n",
    "                    if parts:\n",
    "                        try:\n",
    "                            classes.append(int(parts[0]))\n",
    "                        except ValueError:\n",
    "                            pass\n",
    "\n",
    "        for img_file in dataset['images']:\n",
    "            try:\n",
    "                with Image.open(str(img_file)) as img:\n",
    "                    widths.append(img.width)\n",
    "                    heights.append(img.height)\n",
    "            except Exception:\n",
    "                pass\n",
    "                \n",
    "    return classes, widths, heights, fruit_counts\n",
    "\n",
    "print('Running EDA Data Collection...')\n",
    "classes, widths, heights, fruit_counts = get_class_distributions_and_resolutions(blue_1_files, blue_2_files)\n",
    "print(f'Analyzed {len(widths)} images and {len(classes)} annotations.\\n')\n",
    "\n",
    "def visualize_sample(dataset_files, dataset_name, cls_colors={0: 'lightgreen', 1:'firebrick', 3:'royalblue'}):\n",
    "    images = dataset_files['images']\n",
    "    sample_image_path = random.choice(images)\n",
    "    label_path = sample_image_path.with_suffix('.txt')\n",
    "    \n",
    "    if not label_path.exists():\n",
    "        print(f'Label missing for {sample_image_path}')\n",
    "        return\n",
    "        \n",
    "    try:\n",
    "        img_pil = Image.open(str(sample_image_path))\n",
    "        img = np.array(img_pil)\n",
    "        h, w, _ = img.shape\n",
    "    except Exception:\n",
    "        print('Failed to load image')\n",
    "        return\n",
    "    \n",
    "    fig, ax = plt.subplots(1, figsize=(8, 8))\n",
    "    ax.imshow(img)\n",
    "    \n",
    "    with open(label_path, 'r') as f:\n",
    "        lines = f.readlines()\n",
    "        \n",
    "    for line in lines:\n",
    "        parts = line.strip().split()\n",
    "        if not parts: continue\n",
    "        cls_id = int(parts[0])\n",
    "        x_center, y_center, width, height = map(float, parts[1:])\n",
    "        \n",
    "        x = (x_center - width / 2) * w\n",
    "        y = (y_center - height / 2) * h\n",
    "        box_w = width * w\n",
    "        box_h = height * h\n",
    "        \n",
    "        color = cls_colors.get(cls_id, 'yellow')\n",
    "        rect = patches.Rectangle((x, y), box_w, box_h, linewidth=2, edgecolor=color, facecolor='none')\n",
    "        ax.add_patch(rect)\n",
    "        ax.text(x, y, str(cls_id), color=color, fontsize=12, weight='bold')\n",
    "        \n",
    "    plt.title(f\"Sample from {dataset_name}: {sample_image_path.name}\")\n",
    "    plt.axis('off')\n",
    "    plt.savefig('output_eda_sample.png')\n",
    "    plt.close() # Close plot instead of unblocking show()\n"
]

nb['cells'][2]['source'] = cell2_source

cell3_source = [
    "fig, axs = plt.subplots(1, 3, figsize=(18, 5))\n",
    "\n",
    "# Class Distribution\n",
    "class_counts = Counter(classes)\n",
    "axs[0].bar(class_counts.keys(), class_counts.values())\n",
    "axs[0].set_title('Raw Class Distribution (Before Normalization)')\n",
    "axs[0].set_xlabel('Class ID')\n",
    "axs[0].set_ylabel('Count')\n",
    "axs[0].set_xticks(list(class_counts.keys()))\n",
    "\n",
    "# Image Resolutions\n",
    "axs[1].scatter(widths, heights, alpha=0.5)\n",
    "axs[1].set_title('Image Resolutions')\n",
    "axs[1].set_xlabel('Width')\n",
    "axs[1].set_ylabel('Height')\n",
    "\n",
    "# Fruit Density\n",
    "axs[2].hist(fruit_counts, bins=20)\n",
    "axs[2].set_title('Number of Fruits per Image')\n",
    "axs[2].set_xlabel('Number of Fruits')\n",
    "axs[2].set_ylabel('Frequency')\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.savefig('output_eda_charts.png')\n",
    "plt.close()\n",
    "\n",
    "print(\"Displaying a sample from Blueberry_1 (0=Unripe, 1=Ripe)\")\n",
    "visualize_sample(blue_1_files, 'Blueberry_1')\n",
    "\n",
    "print(\"Displaying a sample from Blueberry_2 (0=Unripe, 3=Ripe)\")\n",
    "visualize_sample(blue_2_files, 'Blueberry_2')\n"
]

nb['cells'][3]['source'] = cell3_source

with open(nb_path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=4)
print('Fixed ipynb')
